#!/bin/bash

# Created by Zac the Wise
# Copied from my railwayAppGDBot and automation repos
# https://github.com/TechWiz-3/automation/blob/main/docker-automation/run_container

# Make the container deletion part a function and make it accessible from the error handler

set -o errexit  # exits if an error occurs

for arg in $"@"
do
    case "${arg}" in
        -d|--delete-other)
            delete_existing=true
            ;;
    esac
done

seperate="------------------------------------------------------------------------"

if [[ $(which tput) ]] ; then
    black_green=$(tput setaf 2 && tput setab 0)  # green foreground black background
    reset=$(tput sgr0)      # resets the entire look
    emphasise=$(tput smso)  # emphasis affect
    bold=$(tput bold)       # bold affect
    yellow=$(tput setaf 3)  # yellow foreground
    purple=$(tput setaf 5)  # purple foreground
# else
#     black_green=
#     reset=
#     emphasise=
#     bold=
#     yellow=
#     purple=
#\033[0m
fi

clear
echo -e "${emphasise}${black_green}Update+run container script created by ${yellow}Zac the Wise ${purple}for simple docker automation\n"
echo $reset"Alrighttyyy, assuming we're in the repo root folder let's get going."
sleep 1

echo $seperate
sleep 1
echo -n "Git pull? [y/n]: "
read pull_ans
if [ "$pull_ans" == "y" ] ; then
    echo $seperate
    echo "GIT PULL"
    sleep 1
    git pull
    sleep 1
    echo $seperate
fi

echo -n "Enter the tag you wish to use: "
read tag

printf "%s\n" "Your tag: $tag"  # if you enter the wrong tag, the sleep will allow an easy Ctrl-C
sleep 2

echo $seperate
sleep 1
echo "${bold}DOCKER BUILD${reset}"
sudo docker build --tag "$tag" .

if [[ "$delete_existing" == "true" ]]
then
    echo "Obtaining existing container ID for deletion"
    container_id=$(sudo docker ps -a --filter "name=NewYearResolutionBot" | awk 'NR==2{print $1}')
    if [[ -z "$container_id" ]]
    then
        echo "No existing containers with same name"
    else
    echo $seperate
    sleep 2
    echo "DOCKER RM"
    sudo docker rm "$container_id"
    echo $seperate
    fi
fi

echo $seperate
sleep 1
echo "${bold}DOCKER RUN${reset}"
sudo docker run -d --name NewYearResolutionBot --network="host" --env-file ./env.list "$tag" || err_no=$?
if [[ $err_no -eq 125 ]] ; then
    echo $seperate
    echo -n "IF the above error says that your selected container name is already taken up then press [y] otherwise press [n] "
    read error_is_same_name
    if [[ "$error_is_same_name" == "y" ]] ; then
        echo -n "Would you like to run the docker run command again but change the name of the container? [y/n] "
        read change_cont_name
        if [[ "$change_cont_name" == "y" ]] ; then
            echo -n "New container name: "
            read new_cont_name
            sleep 2  # affords some time for a Ctrl-C if a mistake occured
            echo $seperate
            sleep 1
            echo "${bold}DOCKER RUN${reset}"
            sudo docker run -d --name "$new_cont_name" --network="host" --env-file ./env.list "$tag"
        else   
            echo $seperate
            sleep 1
            echo "Information about the container with the same name:"
            sleep 1
            sudo docker ps -a --filter "name=NewYearResolutionBot"
            echo $seperate
            echo -n "Would you like to delete it? [y/n] "
            read delete_dupl_cont
            if [[ "$delete_dupl_cont" == "y" ]] ; then
                # in the future, use sed and docker ps to get the container ID for deletion
                echo -n "Please enter container ID as shown above, for deletion: "
                read dupl_cont_id
                sudo docker stop "$dupl_cont_id"
                sudo docker rm "$dupl_cont_id"
                sleep 2
                echo "Initiating docker run command in 2 seconds"
                sleep 2
                echo $seperate
                sleep 1
                echo "${bold}DOCKER RUN${reset}"
                sudo docker run -d --name "NewYearResolutionBot" --network="host" --env-file ./env.list "$tag"
            fi
        fi
    else
        echo -e "No error handling for this exception at the current time, however we would REALLY appreciate it if you reported the issue here https://github.com/TechWiz-3/automation and explain the error, why it occured (if you know) and what would prefer the script do. If you're a more hands on person we'd love it if pull request"
    fi
fi

sleep 1
echo $seperate
echo "Thank you, happy goalbot-ing"
